#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/employee/attendance_record.ddl include/model/db/employee/attendance_record db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace attendance_record_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct record_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "record_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T record_id;
            T& operator()() { return record_id; }
            const T& operator()() const { return record_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct employee_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "employee_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T employee_rk_id;
            T& operator()() { return employee_rk_id; }
            const T& operator()() const { return employee_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T date;
            T& operator()() { return date; }
            const T& operator()() const { return date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::day_point, sqlpp::tag::require_insert>;
    };
    struct clock_in
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "clock_in";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T clock_in;
            T& operator()() { return clock_in; }
            const T& operator()() const { return clock_in; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct clock_out
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "clock_out";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T clock_out;
            T& operator()() { return clock_out; }
            const T& operator()() const { return clock_out; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct leave_type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "leave_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T leave_type;
            T& operator()() { return leave_type; }
            const T& operator()() const { return leave_type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace attendance_record_

  struct attendance_record: sqlpp::table_t<attendance_record,
               attendance_record_::id,
               attendance_record_::record_id,
               attendance_record_::employee_rk_id,
               attendance_record_::date,
               attendance_record_::clock_in,
               attendance_record_::clock_out,
               attendance_record_::status,
               attendance_record_::leave_type,
               attendance_record_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "attendance_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T attendance_record;
        T& operator()() { return attendance_record; }
        const T& operator()() const { return attendance_record; }
      };
    };
  };
} // namespace db
