#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/employee/employee.ddl include/model/db/employee/employee db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace employee_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct employee_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "employee_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T employee_id;
            T& operator()() { return employee_id; }
            const T& operator()() const { return employee_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct user_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "user_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T user_rk_id;
            T& operator()() { return user_rk_id; }
            const T& operator()() const { return user_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct employee_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "employee_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T employee_name;
            T& operator()() { return employee_name; }
            const T& operator()() const { return employee_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct gender
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "gender";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T gender;
            T& operator()() { return gender; }
            const T& operator()() const { return gender; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct birthday
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "birthday";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T birthday;
            T& operator()() { return birthday; }
            const T& operator()() const { return birthday; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::day_point, sqlpp::tag::require_insert>;
    };
    struct id_number
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id_number";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id_number;
            T& operator()() { return id_number; }
            const T& operator()() const { return id_number; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct hire_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "hire_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T hire_date;
            T& operator()() { return hire_date; }
            const T& operator()() const { return hire_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct position_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "position_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T position_rk_id;
            T& operator()() { return position_rk_id; }
            const T& operator()() const { return position_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct address
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "address";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T address;
            T& operator()() { return address; }
            const T& operator()() const { return address; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace employee_

  struct employee: sqlpp::table_t<employee,
               employee_::id,
               employee_::employee_id,
               employee_::user_rk_id,
               employee_::employee_name,
               employee_::gender,
               employee_::birthday,
               employee_::id_number,
               employee_::hire_date,
               employee_::position_rk_id,
               employee_::status,
               employee_::address>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "employee";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T employee;
        T& operator()() { return employee; }
        const T& operator()() const { return employee; }
      };
    };
  };
} // namespace db
