#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/employee/payroll_record.ddl include/model/db/employee/payroll_record db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace payroll_record_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct payroll_record_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "payroll_record_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T payroll_record_id;
            T& operator()() { return payroll_record_id; }
            const T& operator()() const { return payroll_record_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct employee_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "employee_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T employee_rk_id;
            T& operator()() { return employee_rk_id; }
            const T& operator()() const { return employee_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct pay_period
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pay_period";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pay_period;
            T& operator()() { return pay_period; }
            const T& operator()() const { return pay_period; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct basic_salary
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "basic_salary";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T basic_salary;
            T& operator()() { return basic_salary; }
            const T& operator()() const { return basic_salary; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct bonus
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "bonus";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T bonus;
            T& operator()() { return bonus; }
            const T& operator()() const { return bonus; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct deduction
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "deduction";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T deduction;
            T& operator()() { return deduction; }
            const T& operator()() const { return deduction; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct net_salary
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "net_salary";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T net_salary;
            T& operator()() { return net_salary; }
            const T& operator()() const { return net_salary; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct paid_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "paid_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T paid_at;
            T& operator()() { return paid_at; }
            const T& operator()() const { return paid_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
  } // namespace payroll_record_

  struct payroll_record: sqlpp::table_t<payroll_record,
               payroll_record_::id,
               payroll_record_::payroll_record_id,
               payroll_record_::employee_rk_id,
               payroll_record_::pay_period,
               payroll_record_::basic_salary,
               payroll_record_::bonus,
               payroll_record_::deduction,
               payroll_record_::net_salary,
               payroll_record_::paid_at>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "payroll_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T payroll_record;
        T& operator()() { return payroll_record; }
        const T& operator()() const { return payroll_record; }
      };
    };
  };
} // namespace db
