#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/employee/position.ddl include/model/db/employee/position db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace position_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct position_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "position_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T position_id;
            T& operator()() { return position_id; }
            const T& operator()() const { return position_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct position_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "position_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T position_name;
            T& operator()() { return position_name; }
            const T& operator()() const { return position_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct base_salary
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "base_salary";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T base_salary;
            T& operator()() { return base_salary; }
            const T& operator()() const { return base_salary; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct is_manager
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "is_manager";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T is_manager;
            T& operator()() { return is_manager; }
            const T& operator()() const { return is_manager; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::boolean>;
    };
    struct department_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "department_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T department_name;
            T& operator()() { return department_name; }
            const T& operator()() const { return department_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T description;
            T& operator()() { return description; }
            const T& operator()() const { return description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace position_

  struct position: sqlpp::table_t<position,
               position_::id,
               position_::position_id,
               position_::position_name,
               position_::base_salary,
               position_::is_manager,
               position_::department_name,
               position_::description>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "position";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T position;
        T& operator()() { return position; }
        const T& operator()() const { return position; }
      };
    };
  };
} // namespace db
