#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/employee/schedule.ddl include/model/db/employee/schedule db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace schedule_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct schedule_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "schedule_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T schedule_id;
            T& operator()() { return schedule_id; }
            const T& operator()() const { return schedule_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct employee_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "employee_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T employee_rk_id;
            T& operator()() { return employee_rk_id; }
            const T& operator()() const { return employee_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct schedule_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "schedule_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T schedule_date;
            T& operator()() { return schedule_date; }
            const T& operator()() const { return schedule_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::day_point, sqlpp::tag::require_insert>;
    };
    struct start_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "start_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T start_time;
            T& operator()() { return start_time; }
            const T& operator()() const { return start_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_of_day, sqlpp::tag::require_insert>;
    };
    struct end_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "end_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T end_time;
            T& operator()() { return end_time; }
            const T& operator()() const { return end_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_of_day, sqlpp::tag::require_insert>;
    };
    struct created_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_at;
            T& operator()() { return created_at; }
            const T& operator()() const { return created_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point>;
    };
    struct created_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_by;
            T& operator()() { return created_by; }
            const T& operator()() const { return created_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  } // namespace schedule_

  struct schedule: sqlpp::table_t<schedule,
               schedule_::id,
               schedule_::schedule_id,
               schedule_::employee_rk_id,
               schedule_::schedule_date,
               schedule_::start_time,
               schedule_::end_time,
               schedule_::created_at,
               schedule_::created_by>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "schedule";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T schedule;
        T& operator()() { return schedule; }
        const T& operator()() const { return schedule; }
      };
    };
  };
} // namespace db
