#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/myvenv/purchase_order_item.ddl include/model/db/myvenv/purchase_order_item db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace purchase_order_item_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct item_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_id;
            T& operator()() { return item_id; }
            const T& operator()() const { return item_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct purchase_order_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "purchase_order_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T purchase_order_rk_id;
            T& operator()() { return purchase_order_rk_id; }
            const T& operator()() const { return purchase_order_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct unit_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "unit_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T unit_rk_id;
            T& operator()() { return unit_rk_id; }
            const T& operator()() const { return unit_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct unit_price
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "unit_price";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T unit_price;
            T& operator()() { return unit_price; }
            const T& operator()() const { return unit_price; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T quantity;
            T& operator()() { return quantity; }
            const T& operator()() const { return quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct subtotal
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "subtotal";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T subtotal;
            T& operator()() { return subtotal; }
            const T& operator()() const { return subtotal; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
  } // namespace purchase_order_item_

  struct purchase_order_item: sqlpp::table_t<purchase_order_item,
               purchase_order_item_::id,
               purchase_order_item_::item_id,
               purchase_order_item_::purchase_order_rk_id,
               purchase_order_item_::goods_rk_id,
               purchase_order_item_::unit_rk_id,
               purchase_order_item_::unit_price,
               purchase_order_item_::quantity,
               purchase_order_item_::subtotal>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "purchase_order_item";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T purchase_order_item;
        T& operator()() { return purchase_order_item; }
        const T& operator()() const { return purchase_order_item; }
      };
    };
  };
} // namespace db
