#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/supplier/purchase_order.ddl include/model/db/supplier/purchase_order db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace purchase_order_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct purchase_order_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "purchase_order_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T purchase_order_id;
            T& operator()() { return purchase_order_id; }
            const T& operator()() const { return purchase_order_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct supplier_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "supplier_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T supplier_rk_id;
            T& operator()() { return supplier_rk_id; }
            const T& operator()() const { return supplier_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct created_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_at;
            T& operator()() { return created_at; }
            const T& operator()() const { return created_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct created_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_by;
            T& operator()() { return created_by; }
            const T& operator()() const { return created_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct expected_arrival_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "expected_arrival_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T expected_arrival_date;
            T& operator()() { return expected_arrival_date; }
            const T& operator()() const { return expected_arrival_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct actual_arrival_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "actual_arrival_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T actual_arrival_date;
            T& operator()() { return actual_arrival_date; }
            const T& operator()() const { return actual_arrival_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct total_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "total_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T total_amount;
            T& operator()() { return total_amount; }
            const T& operator()() const { return total_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace purchase_order_

  struct purchase_order: sqlpp::table_t<purchase_order,
               purchase_order_::id,
               purchase_order_::purchase_order_id,
               purchase_order_::supplier_rk_id,
               purchase_order_::created_at,
               purchase_order_::created_by,
               purchase_order_::expected_arrival_date,
               purchase_order_::actual_arrival_date,
               purchase_order_::status,
               purchase_order_::total_amount,
               purchase_order_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "purchase_order";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T purchase_order;
        T& operator()() { return purchase_order; }
        const T& operator()() const { return purchase_order; }
      };
    };
  };
} // namespace db
