#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/supplier/supplier.ddl include/model/db/supplier/supplier db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace supplier_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct supplier_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "supplier_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T supplier_id;
            T& operator()() { return supplier_id; }
            const T& operator()() const { return supplier_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct supplier_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "supplier_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T supplier_name;
            T& operator()() { return supplier_name; }
            const T& operator()() const { return supplier_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct contact_person
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "contact_person";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T contact_person;
            T& operator()() { return contact_person; }
            const T& operator()() const { return contact_person; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct phone
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "phone";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T phone;
            T& operator()() { return phone; }
            const T& operator()() const { return phone; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct address
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "address";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T address;
            T& operator()() { return address; }
            const T& operator()() const { return address; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct rating_level
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "rating_level";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T rating_level;
            T& operator()() { return rating_level; }
            const T& operator()() const { return rating_level; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace supplier_

  struct supplier: sqlpp::table_t<supplier,
               supplier_::id,
               supplier_::supplier_id,
               supplier_::supplier_name,
               supplier_::contact_person,
               supplier_::phone,
               supplier_::address,
               supplier_::rating_level>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "supplier";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T supplier;
        T& operator()() { return supplier; }
        const T& operator()() const { return supplier; }
      };
    };
  };
} // namespace db
