#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/supplier/supplier_contract.ddl include/model/db/supplier/supplier_contract db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace supplier_contract_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct contract_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "contract_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T contract_id;
            T& operator()() { return contract_id; }
            const T& operator()() const { return contract_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct supplier_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "supplier_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T supplier_rk_id;
            T& operator()() { return supplier_rk_id; }
            const T& operator()() const { return supplier_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct start_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "start_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T start_date;
            T& operator()() { return start_date; }
            const T& operator()() const { return start_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct end_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "end_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T end_date;
            T& operator()() { return end_date; }
            const T& operator()() const { return end_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct contract_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "contract_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T contract_amount;
            T& operator()() { return contract_amount; }
            const T& operator()() const { return contract_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct file_path
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "file_path";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T file_path;
            T& operator()() { return file_path; }
            const T& operator()() const { return file_path; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace supplier_contract_

  struct supplier_contract: sqlpp::table_t<supplier_contract,
               supplier_contract_::id,
               supplier_contract_::contract_id,
               supplier_contract_::supplier_rk_id,
               supplier_contract_::start_date,
               supplier_contract_::end_date,
               supplier_contract_::contract_amount,
               supplier_contract_::status,
               supplier_contract_::file_path>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "supplier_contract";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T supplier_contract;
        T& operator()() { return supplier_contract; }
        const T& operator()() const { return supplier_contract; }
      };
    };
  };
} // namespace db
