#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/sales/sales_order.ddl include/model/db/sales/sales_order db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace sales_order_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct order_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "order_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T order_id;
            T& operator()() { return order_id; }
            const T& operator()() const { return order_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct sale_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "sale_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T sale_time;
            T& operator()() { return sale_time; }
            const T& operator()() const { return sale_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct cashier_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "cashier_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T cashier_rk_id;
            T& operator()() { return cashier_rk_id; }
            const T& operator()() const { return cashier_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct member_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "member_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T member_rk_id;
            T& operator()() { return member_rk_id; }
            const T& operator()() const { return member_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct total_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "total_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T total_amount;
            T& operator()() { return total_amount; }
            const T& operator()() const { return total_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct paid_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "paid_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T paid_amount;
            T& operator()() { return paid_amount; }
            const T& operator()() const { return paid_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct payment_method
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "payment_method";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T payment_method;
            T& operator()() { return payment_method; }
            const T& operator()() const { return payment_method; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct discount_info
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "discount_info";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T discount_info;
            T& operator()() { return discount_info; }
            const T& operator()() const { return discount_info; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace sales_order_

  struct sales_order: sqlpp::table_t<sales_order,
               sales_order_::id,
               sales_order_::order_id,
               sales_order_::sale_time,
               sales_order_::cashier_rk_id,
               sales_order_::member_rk_id,
               sales_order_::total_amount,
               sales_order_::paid_amount,
               sales_order_::payment_method,
               sales_order_::discount_info,
               sales_order_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "sales_order";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T sales_order;
        T& operator()() { return sales_order; }
        const T& operator()() const { return sales_order; }
      };
    };
  };
} // namespace db
