#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/sales/sales_return_item.ddl include/model/db/sales/sales_return_item db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace sales_return_item_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct item_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_id;
            T& operator()() { return item_id; }
            const T& operator()() const { return item_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct return_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "return_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T return_rk_id;
            T& operator()() { return return_rk_id; }
            const T& operator()() const { return return_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct original_quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "original_quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T original_quantity;
            T& operator()() { return original_quantity; }
            const T& operator()() const { return original_quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct return_quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "return_quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T return_quantity;
            T& operator()() { return return_quantity; }
            const T& operator()() const { return return_quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct refund_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "refund_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T refund_amount;
            T& operator()() { return refund_amount; }
            const T& operator()() const { return refund_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
  } // namespace sales_return_item_

  struct sales_return_item: sqlpp::table_t<sales_return_item,
               sales_return_item_::id,
               sales_return_item_::item_id,
               sales_return_item_::return_rk_id,
               sales_return_item_::goods_rk_id,
               sales_return_item_::original_quantity,
               sales_return_item_::return_quantity,
               sales_return_item_::refund_amount>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "sales_return_item";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T sales_return_item;
        T& operator()() { return sales_return_item; }
        const T& operator()() const { return sales_return_item; }
      };
    };
  };
} // namespace db
