#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/sales/sales_return.ddl include/model/db/sales/sales_return db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace sales_return_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct return_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "return_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T return_id;
            T& operator()() { return return_id; }
            const T& operator()() const { return return_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct order_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "order_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T order_rk_id;
            T& operator()() { return order_rk_id; }
            const T& operator()() const { return order_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct return_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "return_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T return_time;
            T& operator()() { return return_time; }
            const T& operator()() const { return return_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct reason
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "reason";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T reason;
            T& operator()() { return reason; }
            const T& operator()() const { return reason; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct staff_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "staff_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T staff_rk_id;
            T& operator()() { return staff_rk_id; }
            const T& operator()() const { return staff_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct total_refund
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "total_refund";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T total_refund;
            T& operator()() { return total_refund; }
            const T& operator()() const { return total_refund; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace sales_return_

  struct sales_return: sqlpp::table_t<sales_return,
               sales_return_::id,
               sales_return_::return_id,
               sales_return_::order_rk_id,
               sales_return_::return_time,
               sales_return_::reason,
               sales_return_::staff_rk_id,
               sales_return_::total_refund,
               sales_return_::remark,
               sales_return_::status>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "sales_return";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T sales_return;
        T& operator()() { return sales_return; }
        const T& operator()() const { return sales_return; }
      };
    };
  };
} // namespace db
