# 使用 archlinux
FROM fascinatedcow/archlinux AS builder

# 配置代理，这里需要改成自己主机上的代理，我用的是 clash,默认为 7897 端口
# v2raya 默认是 http: 20171 https: 20172。其他的请自行查阅
ENV HTTP_PROXY="http://host.docker.internal:7897" \
  HTTPS_PROXY="https://host.docker.internal:7897"
  
# 配置清华镜像源
RUN echo 'Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist \
  && echo 'Server = https://mirror.archlinuxarm.org/$arch/$repo' >> /etc/pacman.d/mirrorlist

# 安装必要的工具包和项目需要用到的第三方库
RUN pacman -Syu --noconfirm && \
  pacman -S --noconfirm \
  base-devel \
  cmake \
  git \
  vim \
  sqlite \
  mysql \
  openssl \
  pkgconf \
  ninja \
  clang \
  curl \
  asio \
  fmt \
  libsodium \
  nlohmann-json \
  && pacman -Sc --noconfirm

# 创建 builder 用户并将其入组
RUN useradd -m builder && \
  echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# 切换到 builder 用户
USER builder
WORKDIR /home/builder

# 克隆到用户目录
RUN git clone https://aur.archlinux.org/yay-bin.git && \
  cd yay-bin && \
  makepkg -si --noconfirm --skippgpcheck && \
  cd .. && \
  rm -rf yay-bin

# 安装 crow
RUN yay -S --noconfirm crow && \
  yay -Sc --noconfirm

# 清理缓存
USER root
RUN rm -rf /var/cache/pacman/pkg/*

WORKDIR /app

COPY . .
RUN ls -al

# RUN chmod +x ./scripts/install-sqlpp11.sh && \
#   bash ./scripts/install-sqlpp11.sh
