# 使用 x86 架构镜像并通过 Rosetta 转译
FROM --platform=linux/amd64 archlinux:latest AS builder

# 配置代理（确保主机代理已开启）
ENV HTTP_PROXY="http://host.docker.internal:7897" \
    HTTPS_PROXY="http://host.docker.internal:7897"

# 配置清华源（x86 专用）
RUN echo 'Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist

# 使用中科大源
# RUN echo 'Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' >> /etc/pacman.d/mirrorlist

# 更新 CA 证书
RUN pacman -Sy --noconfirm ca-certificates && update-ca-trust

# 更新系统并安装依赖
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
      base-devel \
      cmake \
      git \
      vim \
      tmux \
      sqlite \
      mysql \
      openssl \
      pkgconf \
      ninja \
      clang \
      curl \
      asio \
      fmt \
      libsodium \
      nlohmann-json \
      boost \
    && pacman -Sc --noconfirm


# 创建 builder 用户并将其入组
RUN useradd -m builder && \
  echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# 切换到 builder 用户
USER builder
WORKDIR /home/builder

# 克隆到用户目录
RUN git clone https://aur.archlinux.org/yay-bin.git && \
  cd yay-bin && \
  makepkg -si --noconfirm --skippgpcheck && \
  cd .. && \
  rm -rf yay-bin

# 安装 crow
RUN yay -S --noconfirm crow && \
  yay -Sc --noconfirm

# 清理缓存
USER root
RUN rm -rf /var/cache/pacman/pkg/*

WORKDIR /app

COPY . .
RUN ls -al

RUN chmod +x ./scripts/install-sqlpp11.sh && \
  bash ./scripts/install-sqlpp11.sh
