#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/common/unit.ddl include/model/db/common/unit db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace unit_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct unit_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "unit_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T unit_id;
            T& operator()() { return unit_id; }
            const T& operator()() const { return unit_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct unit_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "unit_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T unit_name;
            T& operator()() { return unit_name; }
            const T& operator()() const { return unit_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace unit_

  struct unit: sqlpp::table_t<unit,
               unit_::id,
               unit_::unit_id,
               unit_::unit_name>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "unit";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T unit;
        T& operator()() { return unit; }
        const T& operator()() const { return unit; }
      };
    };
  };
} // namespace db
