#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming
// sql/finance/budget_plan.ddl include/model/db/finance/budget_plan db

#include <sqlpp11/char_sequence.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/table.h>

namespace db {
namespace budget_plan_ {
  struct id {
    struct _alias_t {
      static constexpr const char _literal[] = "id";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T id;
        T& operator()()
        {
          return id;
        }
        const T& operator()() const
        {
          return id;
        }
      };
    };
    using _traits =
      sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert,
                         sqlpp::tag::must_not_update>;
  };
  struct budget_id {
    struct _alias_t {
      static constexpr const char _literal[] = "budget_id";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T budget_id;
        T& operator()()
        {
          return budget_id;
        }
        const T& operator()() const
        {
          return budget_id;
        }
      };
    };
    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
  };
  struct budget_period {
    struct _alias_t {
      static constexpr const char _literal[] = "budget_period";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T budget_period;
        T& operator()()
        {
          return budget_period;
        }
        const T& operator()() const
        {
          return budget_period;
        }
      };
    };
    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
  };
  struct department_name {
    struct _alias_t {
      static constexpr const char _literal[] = "department_name";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T department_name;
        T& operator()()
        {
          return department_name;
        }
        const T& operator()() const
        {
          return department_name;
        }
      };
    };
    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
  };
  struct budget_type {
    struct _alias_t {
      static constexpr const char _literal[] = "budget_type";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T budget_type;
        T& operator()()
        {
          return budget_type;
        }
        const T& operator()() const
        {
          return budget_type;
        }
      };
    };
    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
  };
  struct budget_amount {
    struct _alias_t {
      static constexpr const char _literal[] = "budget_amount";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T budget_amount;
        T& operator()()
        {
          return budget_amount;
        }
        const T& operator()() const
        {
          return budget_amount;
        }
      };
    };
    using _traits =
      sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
  };
  struct actual_expenditure {
    struct _alias_t {
      static constexpr const char _literal[] = "actual_expenditure";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T actual_expenditure;
        T& operator()()
        {
          return actual_expenditure;
        }
        const T& operator()() const
        {
          return actual_expenditure;
        }
      };
    };
    using _traits =
      sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
  };
  struct create_at {
    struct _alias_t {
      static constexpr const char _literal[] = "create_at";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T create_at;
        T& operator()()
        {
          return create_at;
        }
        const T& operator()() const
        {
          return create_at;
        }
      };
    };
    using _traits =
      sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
  };
  struct responsible_person_id {
    struct _alias_t {
      static constexpr const char _literal[] = "responsible_person_id";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T responsible_person_id;
        T& operator()()
        {
          return responsible_person_id;
        }
        const T& operator()() const
        {
          return responsible_person_id;
        }
      };
    };
    using _traits =
      sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
  };
  struct status {
    struct _alias_t {
      static constexpr const char _literal[] = "status";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T> struct _member_t {
        T status;
        T& operator()()
        {
          return status;
        }
        const T& operator()() const
        {
          return status;
        }
      };
    };
    using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
  };
}  // namespace budget_plan_

struct budget_plan
  : sqlpp::table_t<budget_plan, budget_plan_::id, budget_plan_::budget_id,
                   budget_plan_::budget_period, budget_plan_::department_name,
                   budget_plan_::budget_type, budget_plan_::budget_amount,
                   budget_plan_::actual_expenditure, budget_plan_::create_at,
                   budget_plan_::responsible_person_id, budget_plan_::status> {
  struct _alias_t {
    static constexpr const char _literal[] = "budget_plan";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T budget_plan;
      T& operator()()
      {
        return budget_plan;
      }
      const T& operator()() const
      {
        return budget_plan;
      }
    };
  };
};
}  // namespace db
