#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/finance/cashier_record.ddl include/model/db/finance/cashier_record db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace cashier_record_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct record_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "record_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T record_id;
            T& operator()() { return record_id; }
            const T& operator()() const { return record_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct order_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "order_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T order_rk_id;
            T& operator()() { return order_rk_id; }
            const T& operator()() const { return order_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct cashier_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "cashier_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T cashier_rk_id;
            T& operator()() { return cashier_rk_id; }
            const T& operator()() const { return cashier_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct payment_method
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "payment_method";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T payment_method;
            T& operator()() { return payment_method; }
            const T& operator()() const { return payment_method; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct receivable_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "receivable_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T receivable_amount;
            T& operator()() { return receivable_amount; }
            const T& operator()() const { return receivable_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct paid_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "paid_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T paid_amount;
            T& operator()() { return paid_amount; }
            const T& operator()() const { return paid_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct change_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "change_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T change_amount;
            T& operator()() { return change_amount; }
            const T& operator()() const { return change_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct cashier_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "cashier_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T cashier_time;
            T& operator()() { return cashier_time; }
            const T& operator()() const { return cashier_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct counter_number
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "counter_number";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T counter_number;
            T& operator()() { return counter_number; }
            const T& operator()() const { return counter_number; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace cashier_record_

  struct cashier_record: sqlpp::table_t<cashier_record,
               cashier_record_::id,
               cashier_record_::record_id,
               cashier_record_::order_rk_id,
               cashier_record_::cashier_rk_id,
               cashier_record_::payment_method,
               cashier_record_::receivable_amount,
               cashier_record_::paid_amount,
               cashier_record_::change_amount,
               cashier_record_::cashier_time,
               cashier_record_::counter_number>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "cashier_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T cashier_record;
        T& operator()() { return cashier_record; }
        const T& operator()() const { return cashier_record; }
      };
    };
  };
} // namespace db
