#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/finance/financail_report.ddl include/model/db/finance/financail_report db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace financial_report_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct report_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "report_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T report_id;
            T& operator()() { return report_id; }
            const T& operator()() const { return report_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct report_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "report_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T report_name;
            T& operator()() { return report_name; }
            const T& operator()() const { return report_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct generated_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "generated_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T generated_by;
            T& operator()() { return generated_by; }
            const T& operator()() const { return generated_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct report_type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "report_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T report_type;
            T& operator()() { return report_type; }
            const T& operator()() const { return report_type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct generated_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "generated_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T generated_at;
            T& operator()() { return generated_at; }
            const T& operator()() const { return generated_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct report_start_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "report_start_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T report_start_date;
            T& operator()() { return report_start_date; }
            const T& operator()() const { return report_start_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::day_point, sqlpp::tag::require_insert>;
    };
    struct report_end_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "report_end_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T report_end_date;
            T& operator()() { return report_end_date; }
            const T& operator()() const { return report_end_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::day_point, sqlpp::tag::require_insert>;
    };
    struct file_path
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "file_path";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T file_path;
            T& operator()() { return file_path; }
            const T& operator()() const { return file_path; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace financial_report_

  struct financial_report: sqlpp::table_t<financial_report,
               financial_report_::id,
               financial_report_::report_id,
               financial_report_::report_name,
               financial_report_::generated_by,
               financial_report_::report_type,
               financial_report_::generated_at,
               financial_report_::report_start_date,
               financial_report_::report_end_date,
               financial_report_::file_path>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "financial_report";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T financial_report;
        T& operator()() { return financial_report; }
        const T& operator()() const { return financial_report; }
      };
    };
  };
} // namespace db
