#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/finance/goods_cost_record.ddl include/model/db/finance/goods_cost_record db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace goods_cost_record_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct cost_record_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "cost_record_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T cost_record_id;
            T& operator()() { return cost_record_id; }
            const T& operator()() const { return cost_record_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct stock_in_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "stock_in_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T stock_in_rk_id;
            T& operator()() { return stock_in_rk_id; }
            const T& operator()() const { return stock_in_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct supplier_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "supplier_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T supplier_rk_id;
            T& operator()() { return supplier_rk_id; }
            const T& operator()() const { return supplier_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct unit_cost
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "unit_cost";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T unit_cost;
            T& operator()() { return unit_cost; }
            const T& operator()() const { return unit_cost; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T quantity;
            T& operator()() { return quantity; }
            const T& operator()() const { return quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct total_cost
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "total_cost";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T total_cost;
            T& operator()() { return total_cost; }
            const T& operator()() const { return total_cost; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct stock_in_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "stock_in_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T stock_in_time;
            T& operator()() { return stock_in_time; }
            const T& operator()() const { return stock_in_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct recorded_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "recorded_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T recorded_at;
            T& operator()() { return recorded_at; }
            const T& operator()() const { return recorded_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
  } // namespace goods_cost_record_

  struct goods_cost_record: sqlpp::table_t<goods_cost_record,
               goods_cost_record_::id,
               goods_cost_record_::cost_record_id,
               goods_cost_record_::goods_rk_id,
               goods_cost_record_::stock_in_rk_id,
               goods_cost_record_::supplier_rk_id,
               goods_cost_record_::unit_cost,
               goods_cost_record_::quantity,
               goods_cost_record_::total_cost,
               goods_cost_record_::stock_in_time,
               goods_cost_record_::recorded_at>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "goods_cost_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T goods_cost_record;
        T& operator()() { return goods_cost_record; }
        const T& operator()() const { return goods_cost_record; }
      };
    };
  };
} // namespace db
