#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/finance/tax_record.ddl include/model/db/finance/tax_record db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace tax_record_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct record_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "record_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T record_id;
            T& operator()() { return record_id; }
            const T& operator()() const { return record_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct tax_type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "tax_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T tax_type;
            T& operator()() { return tax_type; }
            const T& operator()() const { return tax_type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct tax_period
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "tax_period";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T tax_period;
            T& operator()() { return tax_period; }
            const T& operator()() const { return tax_period; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct tax_payable
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "tax_payable";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T tax_payable;
            T& operator()() { return tax_payable; }
            const T& operator()() const { return tax_payable; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct tax_paid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "tax_paid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T tax_paid;
            T& operator()() { return tax_paid; }
            const T& operator()() const { return tax_paid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct report_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "report_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T report_rk_id;
            T& operator()() { return report_rk_id; }
            const T& operator()() const { return report_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct declared_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "declared_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T declared_by;
            T& operator()() { return declared_by; }
            const T& operator()() const { return declared_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct paid_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "paid_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T paid_at;
            T& operator()() { return paid_at; }
            const T& operator()() const { return paid_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
  } // namespace tax_record_

  struct tax_record: sqlpp::table_t<tax_record,
               tax_record_::id,
               tax_record_::record_id,
               tax_record_::tax_type,
               tax_record_::tax_period,
               tax_record_::tax_payable,
               tax_record_::tax_paid,
               tax_record_::report_rk_id,
               tax_record_::declared_by,
               tax_record_::status,
               tax_record_::paid_at>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "tax_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T tax_record;
        T& operator()() { return tax_record; }
        const T& operator()() const { return tax_record; }
      };
    };
  };
} // namespace db
