#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/warehouse/inventory_check_item.ddl include/model/db/warehouse/inventory_check_item db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace inventory_check_item_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct item_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_id;
            T& operator()() { return item_id; }
            const T& operator()() const { return item_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct system_quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "system_quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T system_quantity;
            T& operator()() { return system_quantity; }
            const T& operator()() const { return system_quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct actual_quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "actual_quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T actual_quantity;
            T& operator()() { return actual_quantity; }
            const T& operator()() const { return actual_quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct difference
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "difference";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T difference;
            T& operator()() { return difference; }
            const T& operator()() const { return difference; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace inventory_check_item_

  struct inventory_check_item: sqlpp::table_t<inventory_check_item,
               inventory_check_item_::id,
               inventory_check_item_::item_id,
               inventory_check_item_::goods_rk_id,
               inventory_check_item_::system_quantity,
               inventory_check_item_::actual_quantity,
               inventory_check_item_::difference,
               inventory_check_item_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "inventory_check_item";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T inventory_check_item;
        T& operator()() { return inventory_check_item; }
        const T& operator()() const { return inventory_check_item; }
      };
    };
  };
} // namespace db
