#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/warehouse/inventory_item.ddl include/model/db/warehouse/inventory_item db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace inventory_item_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct item_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_id;
            T& operator()() { return item_id; }
            const T& operator()() const { return item_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct inventory_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "inventory_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T inventory_rk_id;
            T& operator()() { return inventory_rk_id; }
            const T& operator()() const { return inventory_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct min_threshold
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "min_threshold";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T min_threshold;
            T& operator()() { return min_threshold; }
            const T& operator()() const { return min_threshold; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct max_threshold
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "max_threshold";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T max_threshold;
            T& operator()() { return max_threshold; }
            const T& operator()() const { return max_threshold; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct last_updated
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "last_updated";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T last_updated;
            T& operator()() { return last_updated; }
            const T& operator()() const { return last_updated; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace inventory_item_

  struct inventory_item: sqlpp::table_t<inventory_item,
               inventory_item_::id,
               inventory_item_::item_id,
               inventory_item_::inventory_rk_id,
               inventory_item_::min_threshold,
               inventory_item_::max_threshold,
               inventory_item_::last_updated,
               inventory_item_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "inventory_item";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T inventory_item;
        T& operator()() { return inventory_item; }
        const T& operator()() const { return inventory_item; }
      };
    };
  };
} // namespace db
