#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/warehouse/inventory_alert.ddl include/model/db/warehouse/inventory_alert db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace inventory_alert_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct lower_bound
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "lower_bound";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T lower_bound;
            T& operator()() { return lower_bound; }
            const T& operator()() const { return lower_bound; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace inventory_alert_

  struct inventory_alert: sqlpp::table_t<inventory_alert,
               inventory_alert_::id,
               inventory_alert_::goods_rk_id,
               inventory_alert_::lower_bound>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "inventory_alert";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T inventory_alert;
        T& operator()() { return inventory_alert; }
        const T& operator()() const { return inventory_alert; }
      };
    };
  };
} // namespace db
