#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/warehouse/inventory_check_order.ddl include/model/db/warehouse/inventory_check_order db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace inventory_check_order_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct warehouse_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "warehouse_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T warehouse_rk_id;
            T& operator()() { return warehouse_rk_id; }
            const T& operator()() const { return warehouse_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct created_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_at;
            T& operator()() { return created_at; }
            const T& operator()() const { return created_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct created_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_by;
            T& operator()() { return created_by; }
            const T& operator()() const { return created_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct audited_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "audited_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T audited_by;
            T& operator()() { return audited_by; }
            const T& operator()() const { return audited_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct audited_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "audited_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T audited_at;
            T& operator()() { return audited_at; }
            const T& operator()() const { return audited_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace inventory_check_order_

  struct inventory_check_order: sqlpp::table_t<inventory_check_order,
               inventory_check_order_::id,
               inventory_check_order_::warehouse_rk_id,
               inventory_check_order_::created_at,
               inventory_check_order_::created_by,
               inventory_check_order_::audited_by,
               inventory_check_order_::audited_at,
               inventory_check_order_::status,
               inventory_check_order_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "inventory_check_order";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T inventory_check_order;
        T& operator()() { return inventory_check_order; }
        const T& operator()() const { return inventory_check_order; }
      };
    };
  };
} // namespace db
