#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/warehouse/stock_in_order.ddl include/model/db/warehouse/stock_in_order db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace stock_in_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct stock_in_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "stock_in_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T stock_in_id;
            T& operator()() { return stock_in_id; }
            const T& operator()() const { return stock_in_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct warehouse_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "warehouse_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T warehouse_rk_id;
            T& operator()() { return warehouse_rk_id; }
            const T& operator()() const { return warehouse_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct created_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_at;
            T& operator()() { return created_at; }
            const T& operator()() const { return created_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct created_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_by;
            T& operator()() { return created_by; }
            const T& operator()() const { return created_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct source_type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "source_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T source_type;
            T& operator()() { return source_type; }
            const T& operator()() const { return source_type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct source_reference
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "source_reference";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T source_reference;
            T& operator()() { return source_reference; }
            const T& operator()() const { return source_reference; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace stock_in_

  struct stock_in: sqlpp::table_t<stock_in,
               stock_in_::id,
               stock_in_::stock_in_id,
               stock_in_::warehouse_rk_id,
               stock_in_::created_at,
               stock_in_::created_by,
               stock_in_::source_type,
               stock_in_::source_reference,
               stock_in_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "stock_in";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T stock_in;
        T& operator()() { return stock_in; }
        const T& operator()() const { return stock_in; }
      };
    };
  };
} // namespace db
