#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/warehouse/stock_out.ddl include/model/db/warehouse/stock_out_order db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace stock_out_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct stock_out_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "stock_out_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T stock_out_id;
            T& operator()() { return stock_out_id; }
            const T& operator()() const { return stock_out_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct warehouse_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "warehouse_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T warehouse_rk_id;
            T& operator()() { return warehouse_rk_id; }
            const T& operator()() const { return warehouse_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct created_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_at;
            T& operator()() { return created_at; }
            const T& operator()() const { return created_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct created_by
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_by";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_by;
            T& operator()() { return created_by; }
            const T& operator()() const { return created_by; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct destination_type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "destination_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T destination_type;
            T& operator()() { return destination_type; }
            const T& operator()() const { return destination_type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct destination_reference
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "destination_reference";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T destination_reference;
            T& operator()() { return destination_reference; }
            const T& operator()() const { return destination_reference; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace stock_out_

  struct stock_out: sqlpp::table_t<stock_out,
               stock_out_::id,
               stock_out_::stock_out_id,
               stock_out_::warehouse_rk_id,
               stock_out_::created_at,
               stock_out_::created_by,
               stock_out_::destination_type,
               stock_out_::destination_reference,
               stock_out_::status,
               stock_out_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "stock_out";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T stock_out;
        T& operator()() { return stock_out; }
        const T& operator()() const { return stock_out; }
      };
    };
  };
} // namespace db
