#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming
// sql/warehouse/warehouse.ddl include/model/db/warehouse/warehouse db

#include <sqlpp11/char_sequence.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/table.h>

namespace db {
namespace warehouse_ {
struct id {
  struct _alias_t {
    static constexpr const char _literal[] = "id";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T id;
      T &operator()() { return id; }
      const T &operator()() const { return id; }
    };
  };
  using _traits =
      sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert,
                         sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
};
struct warehouse_id {
  struct _alias_t {
    static constexpr const char _literal[] = "warehouse_id";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T warehouse_id;
      T &operator()() { return warehouse_id; }
      const T &operator()() const { return warehouse_id; }
    };
  };
  using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};
struct warehouse_name {
  struct _alias_t {
    static constexpr const char _literal[] = "warehouse_name";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T warehouse_name;
      T &operator()() { return warehouse_name; }
      const T &operator()() const { return warehouse_name; }
    };
  };
  using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
};
struct location {
  struct _alias_t {
    static constexpr const char _literal[] = "location";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T location;
      T &operator()() { return location; }
      const T &operator()() const { return location; }
    };
  };
  using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};
struct total_slots {
  struct _alias_t {
    static constexpr const char _literal[] = "total_slots";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T total_slots;
      T &operator()() { return total_slots; }
      const T &operator()() const { return total_slots; }
    };
  };
  using _traits =
      sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
};
struct available_slots {
  struct _alias_t {
    static constexpr const char _literal[] = "available_slots";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T available_slots;
      T &operator()() { return available_slots; }
      const T &operator()() const { return available_slots; }
    };
  };
  using _traits =
      sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
};
struct manager {
  struct _alias_t {
    static constexpr const char _literal[] = "manager";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T manager;
      T &operator()() { return manager; }
      const T &operator()() const { return manager; }
    };
  };
  using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};
struct description {
  struct _alias_t {
    static constexpr const char _literal[] = "description";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T description;
      T &operator()() { return description; }
      const T &operator()() const { return description; }
    };
  };
  using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
};
} // namespace warehouse_

struct warehouse
    : sqlpp::table_t<warehouse, warehouse_::id, warehouse_::warehouse_id,
                     warehouse_::warehouse_name, warehouse_::location,
                     warehouse_::total_slots, warehouse_::available_slots,
                     warehouse_::manager, warehouse_::description> {
  struct _alias_t {
    static constexpr const char _literal[] = "warehouse";
    using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
    template <typename T> struct _member_t {
      T warehouse;
      T &operator()() { return warehouse; }
      const T &operator()() const { return warehouse; }
    };
  };
};
} // namespace db
