#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/warehouse/warehouse.ddl include/model/db/warehouse/warehouse db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace warehouse_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct warehouse_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "warehouse_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T warehouse_id;
            T& operator()() { return warehouse_id; }
            const T& operator()() const { return warehouse_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct warehouse_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "warehouse_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T warehouse_name;
            T& operator()() { return warehouse_name; }
            const T& operator()() const { return warehouse_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct location
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "location";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T location;
            T& operator()() { return location; }
            const T& operator()() const { return location; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct capacity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "capacity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T capacity;
            T& operator()() { return capacity; }
            const T& operator()() const { return capacity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct available_capacity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "available_capacity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T available_capacity;
            T& operator()() { return available_capacity; }
            const T& operator()() const { return available_capacity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct manager_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "manager_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T manager_rk_id;
            T& operator()() { return manager_rk_id; }
            const T& operator()() const { return manager_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct phone
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "phone";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T phone;
            T& operator()() { return phone; }
            const T& operator()() const { return phone; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct created_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_at;
            T& operator()() { return created_at; }
            const T& operator()() const { return created_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct remark
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "remark";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T remark;
            T& operator()() { return remark; }
            const T& operator()() const { return remark; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace warehouse_

  struct warehouse: sqlpp::table_t<warehouse,
               warehouse_::id,
               warehouse_::warehouse_id,
               warehouse_::warehouse_name,
               warehouse_::location,
               warehouse_::capacity,
               warehouse_::available_capacity,
               warehouse_::manager_rk_id,
               warehouse_::phone,
               warehouse_::created_at,
               warehouse_::status,
               warehouse_::remark>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "warehouse";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T warehouse;
        T& operator()() { return warehouse; }
        const T& operator()() const { return warehouse; }
      };
    };
  };
} // namespace db
