#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/goods/goods_price.ddl include/model/db/goods/goods_price db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace goods_price_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct price
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "price";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T price;
            T& operator()() { return price; }
            const T& operator()() const { return price; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct start_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "start_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T start_time;
            T& operator()() { return start_time; }
            const T& operator()() const { return start_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct note
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "note";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T note;
            T& operator()() { return note; }
            const T& operator()() const { return note; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace goods_price_

  struct goods_price: sqlpp::table_t<goods_price,
               goods_price_::id,
               goods_price_::goods_rk_id,
               goods_price_::price,
               goods_price_::start_time,
               goods_price_::note>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "goods_price";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T goods_price;
        T& operator()() { return goods_price; }
        const T& operator()() const { return goods_price; }
      };
    };
  };
} // namespace db
