#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/goods/goods.ddl include/model/db/goods/goods db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace goods_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct goods_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_id;
            T& operator()() { return goods_id; }
            const T& operator()() const { return goods_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct category_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "category_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T category_id;
            T& operator()() { return category_id; }
            const T& operator()() const { return category_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct supplier_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "supplier_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T supplier_id;
            T& operator()() { return supplier_id; }
            const T& operator()() const { return supplier_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct unit_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "unit_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T unit_id;
            T& operator()() { return unit_id; }
            const T& operator()() const { return unit_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct goods_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_name;
            T& operator()() { return goods_name; }
            const T& operator()() const { return goods_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct shelf_life_days
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "shelf_life_days";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T shelf_life_days;
            T& operator()() { return shelf_life_days; }
            const T& operator()() const { return shelf_life_days; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct barcode
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "barcode";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T barcode;
            T& operator()() { return barcode; }
            const T& operator()() const { return barcode; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct image_url
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "image_url";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T image_url;
            T& operator()() { return image_url; }
            const T& operator()() const { return image_url; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T description;
            T& operator()() { return description; }
            const T& operator()() const { return description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace goods_

  struct goods: sqlpp::table_t<goods,
               goods_::id,
               goods_::goods_id,
               goods_::category_id,
               goods_::supplier_id,
               goods_::unit_id,
               goods_::goods_name,
               goods_::shelf_life_days,
               goods_::barcode,
               goods_::image_url,
               goods_::description>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "goods";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T goods;
        T& operator()() { return goods; }
        const T& operator()() const { return goods; }
      };
    };
  };
} // namespace db
