#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/goods/goods_promotion.ddl include/model/db/goods/goods_promotion db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace goods_promotion_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct promotion_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "promotion_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T promotion_rk_id;
            T& operator()() { return promotion_rk_id; }
            const T& operator()() const { return promotion_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct discount_rate
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "discount_rate";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T discount_rate;
            T& operator()() { return discount_rate; }
            const T& operator()() const { return discount_rate; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct full_threshold
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "full_threshold";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T full_threshold;
            T& operator()() { return full_threshold; }
            const T& operator()() const { return full_threshold; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct reduce_amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "reduce_amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T reduce_amount;
            T& operator()() { return reduce_amount; }
            const T& operator()() const { return reduce_amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct buy_quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "buy_quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T buy_quantity;
            T& operator()() { return buy_quantity; }
            const T& operator()() const { return buy_quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct gift_product
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "gift_product";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T gift_product;
            T& operator()() { return gift_product; }
            const T& operator()() const { return gift_product; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace goods_promotion_

  struct goods_promotion: sqlpp::table_t<goods_promotion,
               goods_promotion_::id,
               goods_promotion_::goods_rk_id,
               goods_promotion_::promotion_rk_id,
               goods_promotion_::discount_rate,
               goods_promotion_::full_threshold,
               goods_promotion_::reduce_amount,
               goods_promotion_::buy_quantity,
               goods_promotion_::gift_product>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "goods_promotion";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T goods_promotion;
        T& operator()() { return goods_promotion; }
        const T& operator()() const { return goods_promotion; }
      };
    };
  };
} // namespace db
