#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/goods/goods_category.ddl SuperMarketManagementSystem/include/model/db/goods/goods_category db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace category_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct category_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "category_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T category_id;
            T& operator()() { return category_id; }
            const T& operator()() const { return category_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct category_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "category_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T category_name;
            T& operator()() { return category_name; }
            const T& operator()() const { return category_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct category_description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "category_description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T category_description;
            T& operator()() { return category_description; }
            const T& operator()() const { return category_description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct parent_category_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "parent_category_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T parent_category_id;
            T& operator()() { return parent_category_id; }
            const T& operator()() const { return parent_category_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  } // namespace category_

  struct category: sqlpp::table_t<category,
               category_::id,
               category_::category_id,
               category_::category_name,
               category_::category_description,
               category_::parent_category_id>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "category";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T category;
        T& operator()() { return category; }
        const T& operator()() const { return category; }
      };
    };
  };
} // namespace db
