#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/goods/goods_category.ddl include/model/db/goods/goods_category db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace goods_category_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct goods_category_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_category_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_category_id;
            T& operator()() { return goods_category_id; }
            const T& operator()() const { return goods_category_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct goods_category_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_category_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_category_name;
            T& operator()() { return goods_category_name; }
            const T& operator()() const { return goods_category_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct goods_category_description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_category_description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_category_description;
            T& operator()() { return goods_category_description; }
            const T& operator()() const { return goods_category_description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct parent_category_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "parent_category_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T parent_category_id;
            T& operator()() { return parent_category_id; }
            const T& operator()() const { return parent_category_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  } // namespace goods_category_

  struct goods_category: sqlpp::table_t<goods_category,
               goods_category_::id,
               goods_category_::goods_category_id,
               goods_category_::goods_category_name,
               goods_category_::goods_category_description,
               goods_category_::parent_category_id>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "goods_category";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T goods_category;
        T& operator()() { return goods_category; }
        const T& operator()() const { return goods_category; }
      };
    };
  };
} // namespace db
