#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/goods/inventory.ddl SuperMarketManagementSystem/include/model/db/goods/inventory db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace inventory_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct goods_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_id;
            T& operator()() { return goods_id; }
            const T& operator()() const { return goods_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct warehouse_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "warehouse_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T warehouse_id;
            T& operator()() { return warehouse_id; }
            const T& operator()() const { return warehouse_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T quantity;
            T& operator()() { return quantity; }
            const T& operator()() const { return quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct unit
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "unit";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T unit;
            T& operator()() { return unit; }
            const T& operator()() const { return unit; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace inventory_

  struct inventory: sqlpp::table_t<inventory,
               inventory_::id,
               inventory_::goods_id,
               inventory_::warehouse_id,
               inventory_::quantity,
               inventory_::unit>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "inventory";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T inventory;
        T& operator()() { return inventory; }
        const T& operator()() const { return inventory; }
      };
    };
  };
} // namespace db
