#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/goods/inventory.ddl include/model/db/goods/inventory db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace inventory_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct goods_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "goods_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T goods_rk_id;
            T& operator()() { return goods_rk_id; }
            const T& operator()() const { return goods_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct warehouse_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "warehouse_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T warehouse_rk_id;
            T& operator()() { return warehouse_rk_id; }
            const T& operator()() const { return warehouse_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T quantity;
            T& operator()() { return quantity; }
            const T& operator()() const { return quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct min_threshold
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "min_threshold";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T min_threshold;
            T& operator()() { return min_threshold; }
            const T& operator()() const { return min_threshold; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct max_threshold
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "max_threshold";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T max_threshold;
            T& operator()() { return max_threshold; }
            const T& operator()() const { return max_threshold; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct last_updated
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "last_updated";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T last_updated;
            T& operator()() { return last_updated; }
            const T& operator()() const { return last_updated; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point>;
    };
  } // namespace inventory_

  struct inventory: sqlpp::table_t<inventory,
               inventory_::id,
               inventory_::goods_rk_id,
               inventory_::warehouse_rk_id,
               inventory_::quantity,
               inventory_::min_threshold,
               inventory_::max_threshold,
               inventory_::last_updated>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "inventory";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T inventory;
        T& operator()() { return inventory; }
        const T& operator()() const { return inventory; }
      };
    };
  };
} // namespace db
