-- 财务报表记录表（由系统定期生成）
CREATE TABLE IF NOT EXISTS financial_report (
  id INTEGER PRIMARY KEY AUTOINCREMENT, -- Internal ID（自增主键，内部使用）
  report_id TEXT NOT NULL UNIQUE, -- Report ID（报表ID，外部使用，UUID）
  report_name TEXT NOT NULL, -- Report Name（报表名称）
  generated_by INTEGER NOT NULL, -- Generated By（生成人员）
  report_type TEXT NOT NULL CHECK (
    report_type IN (
      'daily',
      'weekly',
      'monthly',
      'quarterly',
      'yearly'
    )
  ), -- Report Type（报表类型：日报、周报、月报、季报、年报）
  generated_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- Generated At（生成时间）
  report_start_date DATE NOT NULL, -- Report Start Date（报表开始日期）
  report_end_date DATE NOT NULL, -- Report End Date（报表结束日期）
  file_path TEXT NOT NULL, -- File Path（报表文件路径）
  FOREIGN KEY (generated_by) REFERENCES employee (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
