#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/system/role_permission.ddl include/model/db/system/role_permission db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace role_permission_
  {
    struct role_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "role_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T role_rk_id;
            T& operator()() { return role_rk_id; }
            const T& operator()() const { return role_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct permission_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "permission_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T permission_rk_id;
            T& operator()() { return permission_rk_id; }
            const T& operator()() const { return permission_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace role_permission_

  struct role_permission: sqlpp::table_t<role_permission,
               role_permission_::role_rk_id,
               role_permission_::permission_rk_id>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "role_permission";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T role_permission;
        T& operator()() { return role_permission; }
        const T& operator()() const { return role_permission; }
      };
    };
  };
} // namespace db
