#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/system/role.ddl include/model/db/system/role db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace role_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct role_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "role_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T role_id;
            T& operator()() { return role_id; }
            const T& operator()() const { return role_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct role_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "role_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T role_name;
            T& operator()() { return role_name; }
            const T& operator()() const { return role_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T description;
            T& operator()() { return description; }
            const T& operator()() const { return description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct created_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "created_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T created_at;
            T& operator()() { return created_at; }
            const T& operator()() const { return created_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
  } // namespace role_

  struct role: sqlpp::table_t<role,
               role_::id,
               role_::role_id,
               role_::role_name,
               role_::description,
               role_::created_at>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "role";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T role;
        T& operator()() { return role; }
        const T& operator()() const { return role; }
      };
    };
  };
} // namespace db
