#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/system/system_setting.ddl include/model/db/system/system_setting db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace system_setting_
  {
    struct setting_key
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "setting_key";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T setting_key;
            T& operator()() { return setting_key; }
            const T& operator()() const { return setting_key; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct setting_value
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "setting_value";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T setting_value;
            T& operator()() { return setting_value; }
            const T& operator()() const { return setting_value; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T description;
            T& operator()() { return description; }
            const T& operator()() const { return description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct updated_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "updated_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T updated_at;
            T& operator()() { return updated_at; }
            const T& operator()() const { return updated_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct updater_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "updater_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T updater_rk_id;
            T& operator()() { return updater_rk_id; }
            const T& operator()() const { return updater_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
  } // namespace system_setting_

  struct system_setting: sqlpp::table_t<system_setting,
               system_setting_::setting_key,
               system_setting_::setting_value,
               system_setting_::description,
               system_setting_::updated_at,
               system_setting_::updater_rk_id>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "system_setting";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T system_setting;
        T& operator()() { return system_setting; }
        const T& operator()() const { return system_setting; }
      };
    };
  };
} // namespace db
