#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/system/system_log.ddl include/model/db/system/system_log db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace system_log_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct user_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "user_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T user_rk_id;
            T& operator()() { return user_rk_id; }
            const T& operator()() const { return user_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct action_type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "action_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T action_type;
            T& operator()() { return action_type; }
            const T& operator()() const { return action_type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct actual_detail
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "actual_detail";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T actual_detail;
            T& operator()() { return actual_detail; }
            const T& operator()() const { return actual_detail; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct timestamp
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "timestamp";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T timestamp;
            T& operator()() { return timestamp; }
            const T& operator()() const { return timestamp; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct ip_address
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "ip_address";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T ip_address;
            T& operator()() { return ip_address; }
            const T& operator()() const { return ip_address; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct mac_address
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "mac_address";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T mac_address;
            T& operator()() { return mac_address; }
            const T& operator()() const { return mac_address; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace system_log_

  struct system_log: sqlpp::table_t<system_log,
               system_log_::id,
               system_log_::user_rk_id,
               system_log_::action_type,
               system_log_::actual_detail,
               system_log_::timestamp,
               system_log_::ip_address,
               system_log_::mac_address>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "system_log";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T system_log;
        T& operator()() { return system_log; }
        const T& operator()() const { return system_log; }
      };
    };
  };
} // namespace db
