#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/system/system_update_log.ddl include/model/db/system/system_update_log db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace system_update_log_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update>;
    };
    struct external_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "external_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T external_id;
            T& operator()() { return external_id; }
            const T& operator()() const { return external_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct version
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "version";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T version;
            T& operator()() { return version; }
            const T& operator()() const { return version; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct user_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "user_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T user_rk_id;
            T& operator()() { return user_rk_id; }
            const T& operator()() const { return user_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct update_type
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "update_type";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T update_type;
            T& operator()() { return update_type; }
            const T& operator()() const { return update_type; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct updated_at
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "updated_at";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T updated_at;
            T& operator()() { return updated_at; }
            const T& operator()() const { return updated_at; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
    struct description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T description;
            T& operator()() { return description; }
            const T& operator()() const { return description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct change_summary
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "change_summary";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T change_summary;
            T& operator()() { return change_summary; }
            const T& operator()() const { return change_summary; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct affected_modules
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "affected_modules";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T affected_modules;
            T& operator()() { return affected_modules; }
            const T& operator()() const { return affected_modules; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace system_update_log_

  struct system_update_log: sqlpp::table_t<system_update_log,
               system_update_log_::id,
               system_update_log_::external_id,
               system_update_log_::version,
               system_update_log_::user_rk_id,
               system_update_log_::update_type,
               system_update_log_::updated_at,
               system_update_log_::description,
               system_update_log_::change_summary,
               system_update_log_::affected_modules>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "system_update_log";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T system_update_log;
        T& operator()() { return system_update_log; }
        const T& operator()() const { return system_update_log; }
      };
    };
  };
} // namespace db
