#pragma once

// generated by third_party/sqlpp11/scripts/ddl2cpp -identity-naming sql/system/user_role.ddl include/model/db/system/user_role db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace user_role_
  {
    struct user_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "user_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T user_rk_id;
            T& operator()() { return user_rk_id; }
            const T& operator()() const { return user_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct role_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "role_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T role_rk_id;
            T& operator()() { return role_rk_id; }
            const T& operator()() const { return role_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace user_role_

  struct user_role: sqlpp::table_t<user_role,
               user_role_::user_rk_id,
               user_role_::role_rk_id>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "user_role";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T user_role;
        T& operator()() { return user_role; }
        const T& operator()() const { return user_role; }
      };
    };
  };
} // namespace db
