#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/member/member.ddl include/model/db/member/member db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace member_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct member_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "member_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T member_id;
            T& operator()() { return member_id; }
            const T& operator()() const { return member_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct member_phone
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "member_phone";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T member_phone;
            T& operator()() { return member_phone; }
            const T& operator()() const { return member_phone; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct registration_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "registration_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T registration_date;
            T& operator()() { return registration_date; }
            const T& operator()() const { return registration_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct level_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "level_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T level_rk_id;
            T& operator()() { return level_rk_id; }
            const T& operator()() const { return level_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct points
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "points";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T points;
            T& operator()() { return points; }
            const T& operator()() const { return points; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::can_be_null>;
    };
    struct gender
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "gender";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T gender;
            T& operator()() { return gender; }
            const T& operator()() const { return gender; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct birthday
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "birthday";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T birthday;
            T& operator()() { return birthday; }
            const T& operator()() const { return birthday; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::day_point, sqlpp::tag::can_be_null>;
    };
    struct status
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "status";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T status;
            T& operator()() { return status; }
            const T& operator()() const { return status; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
  } // namespace member_

  struct member: sqlpp::table_t<member,
               member_::id,
               member_::member_id,
               member_::member_phone,
               member_::registration_date,
               member_::level_rk_id,
               member_::points,
               member_::gender,
               member_::birthday,
               member_::status>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "member";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T member;
        T& operator()() { return member; }
        const T& operator()() const { return member; }
      };
    };
  };
} // namespace db
