#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/member/member_level.ddl include/model/db/member/member_level db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace member_level_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct level_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "level_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T level_id;
            T& operator()() { return level_id; }
            const T& operator()() const { return level_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct level_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "level_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T level_name;
            T& operator()() { return level_name; }
            const T& operator()() const { return level_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct min_points
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "min_points";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T min_points;
            T& operator()() { return min_points; }
            const T& operator()() const { return min_points; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point>;
    };
    struct discount_rate
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "discount_rate";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T discount_rate;
            T& operator()() { return discount_rate; }
            const T& operator()() const { return discount_rate; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point>;
    };
  } // namespace member_level_

  struct member_level: sqlpp::table_t<member_level,
               member_level_::id,
               member_level_::level_id,
               member_level_::level_name,
               member_level_::min_points,
               member_level_::discount_rate>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "member_level";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T member_level;
        T& operator()() { return member_level; }
        const T& operator()() const { return member_level; }
      };
    };
  };
} // namespace db
