#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/member/member_purchase_record.ddl include/model/db/member/member_purchase_record db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace member_purchase_record_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct record_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "record_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T record_id;
            T& operator()() { return record_id; }
            const T& operator()() const { return record_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct member_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "member_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T member_rk_id;
            T& operator()() { return member_rk_id; }
            const T& operator()() const { return member_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct transaction_date
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "transaction_date";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T transaction_date;
            T& operator()() { return transaction_date; }
            const T& operator()() const { return transaction_date; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct amount
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "amount";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T amount;
            T& operator()() { return amount; }
            const T& operator()() const { return amount; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct earned_points
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "earned_points";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T earned_points;
            T& operator()() { return earned_points; }
            const T& operator()() const { return earned_points; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
  } // namespace member_purchase_record_

  struct member_purchase_record: sqlpp::table_t<member_purchase_record,
               member_purchase_record_::id,
               member_purchase_record_::record_id,
               member_purchase_record_::member_rk_id,
               member_purchase_record_::transaction_date,
               member_purchase_record_::amount,
               member_purchase_record_::earned_points>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "member_purchase_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T member_purchase_record;
        T& operator()() { return member_purchase_record; }
        const T& operator()() const { return member_purchase_record; }
      };
    };
  };
} // namespace db
