#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/member/points_policy.ddl include/model/db/member/points_policy db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace points_policy_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct policy_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "policy_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T policy_id;
            T& operator()() { return policy_id; }
            const T& operator()() const { return policy_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct policy_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "policy_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T policy_name;
            T& operator()() { return policy_name; }
            const T& operator()() const { return policy_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct point_per_yuan
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "point_per_yuan";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T point_per_yuan;
            T& operator()() { return point_per_yuan; }
            const T& operator()() const { return point_per_yuan; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point>;
    };
    struct description
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "description";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T description;
            T& operator()() { return description; }
            const T& operator()() const { return description; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::can_be_null>;
    };
    struct effective_from
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "effective_from";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T effective_from;
            T& operator()() { return effective_from; }
            const T& operator()() const { return effective_from; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct effective_to
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "effective_to";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T effective_to;
            T& operator()() { return effective_to; }
            const T& operator()() const { return effective_to; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::can_be_null>;
    };
  } // namespace points_policy_

  struct points_policy: sqlpp::table_t<points_policy,
               points_policy_::id,
               points_policy_::policy_id,
               points_policy_::policy_name,
               points_policy_::point_per_yuan,
               points_policy_::description,
               points_policy_::effective_from,
               points_policy_::effective_to>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "points_policy";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T points_policy;
        T& operator()() { return points_policy; }
        const T& operator()() const { return points_policy; }
      };
    };
  };
} // namespace db
