#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/member/points_reward_item.ddl include/model/db/member/points_reward_item db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace points_reward_item_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct item_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_id;
            T& operator()() { return item_id; }
            const T& operator()() const { return item_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct item_name
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_name";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_name;
            T& operator()() { return item_name; }
            const T& operator()() const { return item_name; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct points_required
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "points_required";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T points_required;
            T& operator()() { return points_required; }
            const T& operator()() const { return points_required; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct item_quantity
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_quantity";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_quantity;
            T& operator()() { return item_quantity; }
            const T& operator()() const { return item_quantity; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct begin_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "begin_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T begin_time;
            T& operator()() { return begin_time; }
            const T& operator()() const { return begin_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
    struct end_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "end_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T end_time;
            T& operator()() { return end_time; }
            const T& operator()() const { return end_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
  } // namespace points_reward_item_

  struct points_reward_item: sqlpp::table_t<points_reward_item,
               points_reward_item_::id,
               points_reward_item_::item_id,
               points_reward_item_::item_name,
               points_reward_item_::points_required,
               points_reward_item_::item_quantity,
               points_reward_item_::begin_time,
               points_reward_item_::end_time>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "points_reward_item";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T points_reward_item;
        T& operator()() { return points_reward_item; }
        const T& operator()() const { return points_reward_item; }
      };
    };
  };
} // namespace db
