#pragma once

// generated by /bin/sqlpp11-ddl2cpp -identity-naming sql/member/points_exchange_record.ddl include/model/db/member/points_exchange_record db

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace db
{
  namespace points_exchange_record_
  {
    struct id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct record_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "record_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T record_id;
            T& operator()() { return record_id; }
            const T& operator()() const { return record_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct member_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "member_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T member_rk_id;
            T& operator()() { return member_rk_id; }
            const T& operator()() const { return member_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct item_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "item_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T item_rk_id;
            T& operator()() { return item_rk_id; }
            const T& operator()() const { return item_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct operator_rk_id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "operator_rk_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T operator_rk_id;
            T& operator()() { return operator_rk_id; }
            const T& operator()() const { return operator_rk_id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
    struct points_spent
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "points_spent";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T points_spent;
            T& operator()() { return points_spent; }
            const T& operator()() const { return points_spent; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::floating_point, sqlpp::tag::require_insert>;
    };
    struct redemption_time
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "redemption_time";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T redemption_time;
            T& operator()() { return redemption_time; }
            const T& operator()() const { return redemption_time; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::time_point, sqlpp::tag::require_insert>;
    };
  } // namespace points_exchange_record_

  struct points_exchange_record: sqlpp::table_t<points_exchange_record,
               points_exchange_record_::id,
               points_exchange_record_::record_id,
               points_exchange_record_::member_rk_id,
               points_exchange_record_::item_rk_id,
               points_exchange_record_::operator_rk_id,
               points_exchange_record_::points_spent,
               points_exchange_record_::redemption_time>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "points_exchange_record";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T points_exchange_record;
        T& operator()() { return points_exchange_record; }
        const T& operator()() const { return points_exchange_record; }
      };
    };
  };
} // namespace db
